user :
  name_length: 50
  email_length: 255
  password_length: 6
  vavatar_size: 80
  remember: "1"
  user_size: 50
  hours: 2
microposts :
  content_maximum: 140
  gravatar_for: 50
  picture_size: 5
shared:
  current_user: 50
